/* 取消环节 */
export enum DESIGN_PROCESSING_STEP_ENUM {
  DESIGN_CODE = '100',
  MATERIAL_CONFIRM = '130',
  DEVELOP_BOM = '150',
  PURCHASE_APPLY_FOLLOW = '170',
}
export const DESIGN_PROCESSING_STEP_LIST = [
  { value: DESIGN_PROCESSING_STEP_ENUM.DESIGN_CODE, label: '设计打版' },
  { value: DESIGN_PROCESSING_STEP_ENUM.MATERIAL_CONFIRM, label: '物料确认跟进' },
  { value: DESIGN_PROCESSING_STEP_ENUM.DEVELOP_BOM, label: '开发BOM' },
  { value: DESIGN_PROCESSING_STEP_ENUM.PURCHASE_APPLY_FOLLOW, label: '采购申请' },
];
