import { App } from 'vue';

import AddressPicker from '@/components/address-picker';
import Pagination from '@/components/pagination';
import Upload from '@/components/upload/index';
import InputNumber from '@/components/input-number';
import InputNumberRanger from '@/components/input-number-ranger';
import QuerySelect from '@/components/query-select';
import Empty from '@/components/empty';
import Tabs from '@/components/tabs';
import SearchArea from '@/components/search-area';
import HeaderArea from '@/components/header-area';
import DetailTitle from '@/components/detail-title';
import CustomLogs from '@/components/custom-logs';
import DictionarySelect from '@/components/dictionary-select';
import Uploader from '@/components/uploader/index';
import CustomImage from '@/components/custom-image/index';
import OperationDrawer from '@/components/operation-drawer';
import ImageViewer from '@/components/image-viewer';
import { CustomForm } from '@/components/custom-form';
import CustomDesc from '@/components/custom-desc';
import Operation from '@/components/operation';
import RemarkRecord from '@/components/remark-record';
import RadioCheckbox from '@/components/radio-checkbox';
import DatePicker from '@/components/date-picker';
import CustomTable from '@/components/custom-table';
import PageCard from '@/components/page-card';
import NumberBasis from '@/components/number-basis';
import LeftMenuTree from '@/components/left-menu-tree';
import ResponesiveRow from '@/components/responsive-row';
import ColorCascader from '@/components/color-cascader';
import CoContentCard from '@/components/content-card';

export default function componentsInstall(app: App) {
  app.use(AddressPicker);
  app.use(Pagination);
  app.use(Upload);
  app.use(InputNumber);
  app.use(InputNumberRanger);
  app.use(QuerySelect);
  app.use(Empty);
  app.use(Tabs);
  app.use(SearchArea);
  app.use(HeaderArea);
  app.use(DetailTitle);
  app.use(CustomLogs);
  app.use(DictionarySelect);
  app.use(Uploader);
  app.use(CustomImage);
  app.use(OperationDrawer);
  app.use(ImageViewer);
  app.use(CustomForm);
  app.use(CustomDesc);
  app.use(Operation);
  app.use(RemarkRecord);
  app.use(RadioCheckbox);
  app.use(DatePicker);
  app.use(CustomTable);
  app.use(PageCard);
  app.use(NumberBasis);
  app.use(LeftMenuTree);
  app.use(ResponesiveRow);
  app.use(ColorCascader);
  app.use(CoContentCard);
}
