[versions]
easyexcel = "3.1.5"
easypoi_base = "4.3.0"
bfg = "1.0.0-RELEASE"
tracker-micrometer = "0.0.1-RELEASE"
butted-sdk-version = "3.4.1-RELEASE"
#butted-sdk-version = "3.3.6-RELEASE"
aliyun-dashvector = "1.0.18"
[libraries]
easyexcel = { group = "com.alibaba", name = "easyexcel", version.ref = "easyexcel" }
easypoi_base = { group = "cn.afterturn", name = "easypoi-base", version.ref = "easypoi_base" }
bfg-sdk = { module = "tech.tiangong.bfg:bfg-sdk", version.ref = "bfg" }
tracker-micrometer = { module = "com.zjkj.tracker:tracker-micrometer", version.ref = "tracker-micrometer" }
tech-butted-sdk = { module = "tech.tiangong.butted:butted-sdk", version.ref = "butted-sdk-version" }
aliyun-dashvector-java-sdk = { module = "com.aliyun:dashvector-java-sdk", version.ref = "aliyun-dashvector" }