import { IRouteConfig } from '@/router/types';

export default [
  {
    path: '/base-config',
    name: 'BaseConfig',
    component: () => import('@/layouts/main/index.vue'),
    redirect: 'BaseConfigSizePosition',
    meta: {
      title: '基础配置',
      icon: 'components',
      noCache: false,
      auth: true,
    },
    children: [
      {
        path: 'size-position',
        name: 'BaseConfigSizePosition',
        component: () => import('@/modules/base-config/views/size-position/list.vue'),
        meta: {
          title: '部位名称',
          noCache: false,
          auth: true,
          activeMenu: 'BaseConfigSizePosition',
        },
      },
      {
        path: 'design-group',
        name: 'BaseConfigDesignGroup',
        component: () => import('@/modules/base-config/views/design-group/list.vue'),
        meta: {
          title: '设计组别',
          noCache: false,
          auth: true,
          activeMenu: 'BaseConfigDesignGroup',
        },
      },
      {
        path: 'paper-group',
        name: 'BaseConfigPaperGroup',
        component: () => import('@/modules/base-config/views/paper-group/list.vue'),
        meta: {
          title: '纸样组别',
          noCache: false,
          auth: true,
          activeMenu: 'BaseConfigPaperGroup',
        },
      },
      {
        path: 'responsible-dept',
        name: 'BaseConfigResponsibleDept',
        component: () => import('@/modules/base-config/views/responsible-dept/list.vue'),
        meta: {
          title: '异常责任部门',
          noCache: false,
          auth: true,
          activeMenu: 'BaseConfigResponsibleDept',
        },
      },
      {
        path: 'fee-ratio',
        name: 'BaseConfigFeeRatio',
        component: () => import('@/modules/base-config/views/fee-ratio/list.vue'),
        meta: {
          title: '外发版费倍率',
          noCache: false,
          auth: true,
          activeMenu: 'BaseConfigFeeRatio',
        },
      },
      {
        path: 'repair-responsible',
        name: 'BaseConfigRepairResponsible',
        component: () => import('@/modules/base-config/views/repair-responsible/list.vue'),
        meta: {
          title: '返修/复版责任方',
          noCache: false,
          auth: true,
          activeMenu: 'BaseConfigRepairResponsible',
        },
      },
      // {
      //   path: 'size-template',
      //   name: 'BaseConfigSizeTemplate',
      //   component: () => import('@/modules/base-config/views/size-template/list.vue'),
      //   meta: {
      //     title: '尺寸表模板',
      //     noCache: false,
      //     auth: true,
      //     activeMenu: 'BaseConfigSizeTemplate',
      //   },
      // },
      {
        path: 'size-template/detail',
        name: 'BaseConfigSizeTemplateDetail',
        component: () => import('@/modules/base-config/views/size-template/detail.vue'),
        meta: {
          title: '尺寸表模板详情',
          noCache: false,
          auth: true,
          activeMenu: 'BaseConfigSizeTemplate',
        },
      },
      {
        path: 'process-style',
        name: 'BaseConfigProcessStyle',
        component: () => import('@/modules/base-config/views/process-style/list.vue'),
        meta: {
          title: '工序款式库',
          noCache: false,
          auth: true,
          activeMenu: 'BaseConfigProcessStyle',
        },
      },
      {
        path: 'process-style/detail',
        name: 'BaseConfigProcessStyleDetail',
        component: () => import('@/modules/base-config/views/process-style/detail.vue'),
        meta: {
          title: '工序款式库详情',
          noCache: false,
          auth: true,
          activeMenu: 'BaseConfigProcessStyle',
        },
      },
      {
        path: 'sewing-component',
        name: 'BaseConfigSewingComponent',
        component: () => import('@/modules/base-config/views/sewing-component/list.vue'),
        meta: {
          title: '工序部件库',
          noCache: false,
          auth: true,
          activeMenu: 'BaseConfigSewingComponent',
        },
      },
      {
        path: 'sewing-component/detail',
        name: 'BaseConfigSewingComponentDetail',
        component: () => import('@/modules/base-config/views/sewing-component/detail.vue'),
        meta: {
          title: '工序部件库详情',
          noCache: false,
          auth: true,
          activeMenu: 'BaseConfigSewingComponent',
        },
      },
      {
        path: 'cancel-reason',
        name: 'BaseConfigCancelReason',
        component: () => import('@/modules/base-config/views/cancel-reason/list.vue'),
        meta: {
          title: '取消原因',
          noCache: false,
          auth: true,
          activeMenu: 'BaseConfigCancelReason',
        },
      },
      {
        path: 'color-library',
        name: 'BaseConfigColorLibrary',
        component: () => import('@/modules/base-config/views/color-library/list.vue'),
        meta: {
          title: '颜色库',
          noCache: false,
          auth: true,
          activeMenu: 'BaseConfigColorLibrary',
        },
      },
      {
        path: 'size-relationship-maintenance',
        name: 'BaseConfigSizeRelationshipMaintenance',
        component: () => import('@/modules/base-config/views/size-relationship-maintenance/list.vue'),
        meta: {
          title: '尺码关系维护',
          noCache: false,
          auth: true,
          activeMenu: 'BaseConfigSizeRelationshipMaintenance',
        },
      },
      {
        path: 'ai-category-mapping',
        name: 'BaseConfigAICategoryMapping',
        component: () => import('@/modules/base-config/views/ai-category-mapping/views/list.vue'),
        meta: {
          title: 'AI品类映射',
          noCache: false,
          auth: true,
          activeMenu: 'BaseConfigAICategoryMapping',
        },
      },
      {
        path: 'size-chart-template',
        name: 'BaseConfigSizeChartTemplate',
        component: () => import('@/modules/base-config/views/size-chart-template/views/list.vue'),
        meta: {
          title: '尺寸表模板图',
          noCache: false,
          auth: true,
          activeMenu: 'BaseConfigSizeChartTemplate',
        },
      },
      {
        path: 'audit-craft-component-library',
        name: 'BaseConfigAuditCraftComponentLibrary',
        component: () => import('@/modules/base-config/views/audit-craft-component-library/views/list.vue'),
        meta: {
          title: '审版工艺部件库',
          noCache: false,
          auth: true,
          activeMenu: 'BaseConfigAuditCraftComponentLibrary',
        },
      },
      {
        path: 'audit-craft-component-library/new',
        name: 'NewBaseConfigAuditCraftComponentLibrary',
        component: () => import('@/modules/base-config/views/audit-craft-component-library/views/edit.vue'),
        meta: {
          title: '新增审版工艺部件',
          noCache: false,
          auth: true,
          activeMenu: 'BaseConfigAuditCraftComponentLibrary',
        },
      },
      {
        path: 'audit-craft-component-library/edit/:id',
        name: 'EditBaseConfigAuditCraftComponentLibrary',
        component: () => import('@/modules/base-config/views/audit-craft-component-library/views/edit.vue'),
        meta: {
          title: '编辑审版工艺部件',
          noCache: false,
          auth: true,
          activeMenu: 'BaseConfigAuditCraftComponentLibrary',
        },
      },
      {
        path: 'audit-craft-component-library/detail/:id',
        name: 'BaseConfigAuditCraftComponentLibraryDetail',
        component: () => import('@/modules/base-config/views/audit-craft-component-library/views/edit.vue'),
        meta: {
          title: '审版工艺部件详情',
          noCache: false,
          auth: true,
          activeMenu: 'BaseConfigAuditCraftComponentLibrary',
        },
      },
      {
        path: 'audit-craft-component-style-library',
        name: 'BaseConfigAuditCraftComponentStyleLibrary',
        component: () => import('@/modules/base-config/views/audit-craft-component-style-library/views/list.vue'),
        meta: {
          title: '审版工艺款式库',
          noCache: false,
          auth: true,
          activeMenu: 'BaseConfigAuditCraftComponentStyleLibrary',
        },
      },
      {
        path: 'audit-craft-component-style-library/new',
        name: 'NewBaseConfigAuditCraftComponentStyleLibrary',
        component: () => import('@/modules/base-config/views/audit-craft-component-style-library/views/edit.vue'),
        meta: {
          title: '新增审版工艺款式',
          noCache: false,
          auth: true,
          activeMenu: 'BaseConfigAuditCraftComponentStyleLibrary',
        },
      },
      {
        path: 'audit-craft-component-style-library/edit/:id',
        name: 'EditBaseConfigAuditCraftComponentStyleLibrary',
        component: () => import('@/modules/base-config/views/audit-craft-component-style-library/views/edit.vue'),
        meta: {
          title: '编辑审版工艺款式',
          noCache: false,
          auth: true,
          activeMenu: 'BaseConfigAuditCraftComponentStyleLibrary',
        },
      },
      {
        path: 'audit-craft-component-style-library/detail/:id',
        name: 'BaseConfigAuditCraftComponentStyleLibraryDetail',
        component: () => import('@/modules/base-config/views/audit-craft-component-style-library/views/edit.vue'),
        meta: {
          title: '审版工艺款式详情',
          noCache: false,
          auth: true,
          activeMenu: 'BaseConfigAuditCraftComponentStyleLibrary',
        },
      },
      {
        path: 'shop',
        name: 'BaseConfigShop',
        component: () => import('@/modules/base-config/shop/views/list/index.vue'),
        meta: {
          title: '店铺管理',
          noCache: false,
          auth: true,
          activeMenu: 'BaseConfigShop',
        },
      },
      {
        path: 'size-template',
        name: 'BaseConfigSizeTemplateList',
        component: () => import('./size-template/views/list/index.vue'),
        meta: {
          title: '尺码表模板列表',
          auth: true,
          isKeepAlive: true,
        },
      },
      {
        path: 'size-diff',
        name: 'BaseConfigSizeDiffList',
        component: () => import('./size-diff/views/list/index.vue'),
        meta: {
          title: '档差规则',
          auth: true,
          isKeepAlive: true,
        },
      },
      {
        path: 'category/list',
        name: 'BaseConfigCategoryList',
        component: () => import('./category/views/list/index.vue'),
        meta: {
          title: '品类管理',
          auth: true,
          isKeepAlive: true,
        },
      },
    ],
  },
] as IRouteConfig[];
