/* eslint-disable vue/max-len */
import { currentEnv } from '@/core/http/env';

export enum ROUTER_TYPE_ENUM {
  BACK = 'back',
}

export const defaultQaToken = 'eyJzb3VyY2UiOiJTU08iLCJhbGciOiJSUzI1NiJ9.eyJtdCI6MSwic3NvVXNlciI6IntcInJlYWxOYW1lXCI6XCJKVumAmueUqOeUqOaIt1wiLFwidXNlcklkXCI6XCIxMDEwMTAxMDFcIixcInVzZXJDb2RlXCI6XCIwMDAwMDAwMTAwNTYwXCIsXCJ1c2VybmFtZVwiOlwiSlbpgJrnlKjnlKjmiLdcIn0iLCJleHAiOjQ4NzY0NDgxMDV9.ruP8wxChr3eJEEzuHdNW59-zxjj3StTooKOaAGmq-N3mmFU7ky1PutrgRPx_a2e-jTlSw1_8-yg7GaVlyePkmoTukESkcitytT_yxwHrfgAhO2Ebo1q49TNhoEtTPs0ubDk7lzG24NbJnYS4E96XvEmSVPAI7HjjbtRq0zl8S0ZdheleHejProbdCFM4YI6qBQ7wYxPzhh8wECiY-lfvrwK9paS57cQ6bzDFeJF0SkkubA17uzE5sQHkjCfRgECFXeIK_3VPPx0HSmEiaP0RlsXzXjbzl8rwv1v3ABP8k5O_FD7qmjooxtdy_ZdlCxR2Akty-5RvXPpE61NKzshYPw';
export const defaultUatToken = 'eyJzb3VyY2UiOiJTU08iLCJhbGciOiJSUzI1NiJ9.eyJtdCI6MSwic3NvVXNlciI6IntcInJlYWxOYW1lXCI6XCJKVumAmueUqOeUqOaIt1wiLFwidXNlcklkXCI6XCIxMDEwMTAxMDFcIixcInVzZXJDb2RlXCI6XCIwMDAwMDAwMTAwNTYwXCIsXCJ1c2VybmFtZVwiOlwiSlbpgJrnlKjnlKjmiLdcIn0iLCJleHAiOjQ4NzY0NDg3MDV9.e60QxHmsX9pJfrcgObLuvA2Y9r5wFrvrzOmoreUQgIClo7aD4Lf8I-_DLu7pBdyXsdztxFFP3hTOjF3v_dpAbASCyAT_RAhk7pBWZokZautMSEGVpfsbYB61xSUowf6xHm13u8Skt40BMVYBoZbB0AFFbEwkTuL6fQ-GT8r0Ayv2VdpH155lJi4QwY3uq6mfglGtDNbVM3iBH-0_umbEWVS3k5SwJtqghAfnkZdlm8RwBh2s0S4utjq1-dcgPM0YZco-20T-m_8fS7WNXvdabFMBBl4ra5ULuVgA2kaskzT9vHKuBdoX34tVB_Z8ElMlp8bfxR7U6lEBzHMHcp-Xpw';
export const defaultToken = 'eyJzb3VyY2UiOiJTU08iLCJhbGciOiJSUzI1NiJ9.eyJtdCI6MSwic3NvVXNlciI6IntcInJlYWxOYW1lXCI6XCJKVumAmueUqOeUqOaIt1wiLFwidXNlcklkXCI6XCIxMDEwMTAxMDFcIixcInVzZXJDb2RlXCI6XCIwMDAwMDAwMTAwNTYwXCIsXCJ1c2VybmFtZVwiOlwiSlbpgJrnlKjnlKjmiLdcIn0iLCJleHAiOjQ4NzY0NDg3NjR9.LciDg8dyaNfY9Yp4PtzlLbq4xVQiM-ZcyMYXQvqWQZQa0u8gGPdX5jtft6dK144t577v7OxbPqUj43P5GMhKTshShDwFqzc_Mn6poxMC2AgNvWXddB9mWeYXjo2-V-WhxgiujOSUqJXEmtToGSeUtt0Q3XogkGnBPoBf9y4keBG9g2S99M4jKR8PgMkrraCENnYG4P_y_ZQzPP4k19LEo7rR7uCo4WHw1YBICMYoqcLJ7M4neDLc6K1W6jvo9MlNYeoFZi_xQWVXOd3BHh1Ib_oDm_CpR7ZO_XWwPRpnV9nQM6DrqxEeVGep_UwergOZ8ybI6i_oVfVDj3jQU4-Fsg';

export const getDefaultToken = () => {
  if (currentEnv.includes('dev')) {
    return defaultQaToken;
  }
  if (currentEnv.includes('qa')) {
    return defaultQaToken;
  }
  if (currentEnv.includes('uat')) {
    return defaultUatToken;
  }
  return defaultToken;
};
