package tech.tiangong.sdp.vo.resp;

import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;
import lombok.experimental.SuperBuilder;
import java.io.Serial;
import java.io.Serializable;
import java.util.List;

/**
 * @author liuhongfu
 */
@Data
public class ColorCategoryVO implements Serializable {

    @Serial
    private static final long serialVersionUID = 7004855187305100586L;


    /**
     * 品类名称
     */
    private String name;

    /**
     * 品类编码
     */
    private String code;

    /**
     * 颜色列表
     */
    private List<ColorResp> colorRespList;


    /**
     * 颜色响应DTO
     *
     * @author Generated By YAPI Schema
     */
    @Data
    @SuperBuilder
    @Accessors(chain = true)
    @NoArgsConstructor
    public static class ColorResp implements Serializable {

        @Serial
        private static final long serialVersionUID = -3572155942378577417L;

        /**
         * 颜色名称
         */
        private String name;

        /**
         * 颜色编码
         */
        private String code;

    }

}
