package tech.tiangong.sdp.vo.resp;

import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;
import lombok.experimental.SuperBuilder;
import java.io.Serial;
import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;

/**
 * @author liuhongfu
 */
@Data
public class ColorCategoryResp implements Serializable {

    @Serial
    private static final long serialVersionUID = 7004855187305100586L;

    /**
     * 颜色类别表id
     */
    private Long colorCategoryId;

    /**
     * 颜色类别名称
     */
    private String colorCategoryName;

    /**
     * 编号
     */
    private String colorCategoryCode;

    /**
     * 示意图
     */
    private String colorCategoryDiagramUrl;

    /**
     * 完整示意图url
     */
    private String fullColorCategoryDiagramUrl;

    /**
     * 颜色类别序号
     */
    private BigDecimal colorCategoryNumber;

    /**
     * 颜色列表
     */
    private List<ColorResp> colorRespList;


    /**
     * 颜色响应DTO
     *
     * @author Generated By YAPI Schema
     */
    @Data
    @SuperBuilder
    @Accessors(chain = true)
    @NoArgsConstructor
    public static class ColorResp implements Serializable {

        @Serial
        private static final long serialVersionUID = -3572155942378577417L;

        /**
         * 颜色表id
         */
        private Long colorId;

        /**
         * 颜色类别表id
         */
        private Long colorCategoryId;

        /**
         * 颜色名称
         */
        private String color;

        /**
         * 编号
         */
        private String colorCode;

        /**
         * 色号
         */
        private String colorNumber;

        /**
         * 示意图
         */
        private String colorDiagramUrl;

        /**
         * 完整示意图url
         */
        private String fullColorDiagramUrl;

        /**
         * 修改时间
         */
        private LocalDateTime revisedTime;

        /**
         * 修改人名称
         */
        private String reviserName;

    }

}
