// 齐套环节
export enum MATERIAL_KITTING_STATE_ENUM {
  WAIT_FOR_ALL = '100',
  TO_BE_DELIVERED = '110',
  TO_BE_SIGNED = '120',
  ALREADY_SIGN_FOR = '130',
  CLOSED = '140',
}
export const MATERIAL_KITTING_STATE_LIST = [
  { value: MATERIAL_KITTING_STATE_ENUM.WAIT_FOR_ALL, label: '待齐套' },
  { value: MATERIAL_KITTING_STATE_ENUM.TO_BE_DELIVERED, label: '待发货' },
  { value: MATERIAL_KITTING_STATE_ENUM.TO_BE_SIGNED, label: '待签收' },
  { value: MATERIAL_KITTING_STATE_ENUM.ALREADY_SIGN_FOR, label: '已签收' },
  { value: MATERIAL_KITTING_STATE_ENUM.CLOSED, label: '已关闭' },
];
